export const FETCHING_INTERESTS = "FETCHING_INTERESTS";
export const FETCHING_INTERESTS_SUCCESS = "FETCHING_INTERESTS_SUCCESS";
export const FETCHING_INTERESTS_FAILURE = "FETCHING_INTERESTS_FAILURE";
